server:
  port: 81

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie_ticket_system?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8

-Ddruid:
  mysql:
    usePingMethod: false

mybatis-plus:
  global-config:
    db-config:
      id-type: auto

files:
  upload:
    path: D:\YYC\upload\